name: Delete Old Packages
on:
  workflow_dispatch: # Позволяет запускать процесс вручную кнопкой

jobs:
  clean-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete deployment packages
        env:
          # Обязательно используйте ваш PAT-токен с правами delete:packages
          GH_TOKEN: ${{ secrets.CR_PAT }} 
          PACKAGE_NAME: 'amneziawg-dockerhub/amneziawg-scratch'
        run: |
          # Автоматически заменяем '/' на '%2F' для корректного запроса к API GitHub
          ENCODED_NAME="${PACKAGE_NAME////%2F}"
          
          echo "Работаем с пакетом: $PACKAGE_NAME (API путь: $ENCODED_NAME)"
          
          # Получаем список всех версий пакета
          VERSIONS=$(gh api "/user/packages/container/$ENCODED_NAME/versions" --paginate --jq '.[] | .id')
          
          VERSION_IDS=($VERSIONS)
          echo "Найдено всего версий: ${#VERSION_IDS[@]}"
          
          if [ ${#VERSION_IDS[@]} -le 1 ]; then
            echo "Удалять нечего, осталась 1 версия или меньше."
            exit 0
          fi
          
          # Удаляем все версии, кроме первой (самой новой)
          for id in "${VERSION_IDS[@]:1}"; do
            echo "Удаляю версию контейнера с ID: $id..."
            gh api --method DELETE "/user/packages/container/$ENCODED_NAME/versions/$id" --silent || true
          done
          
          echo "Очистка успешно завершена!"
